#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_LETSENCRYPT_APP_PATH="/etc/letsencrypt/"
LETSENCRYPT_CRON="/etc/cron.d/openmediavault-letsencrypt"

case "$1" in
    purge)
        if [ -d "${OMV_LETSENCRYPT_APP_PATH}" ]; then
            rm -rf "${OMV_LETSENCRYPT_APP_PATH}"
        fi

        if [ -f "${LETSENCRYPT_CRON}" ]; then
            rm -f "${LETSENCRYPT_CRON}"
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
