#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_LETSENCRYPT_APP_PATH="/opt/letsencrypt/"

case "$1" in
    purge)
        SERVICE_XPATH_NAME="letsencrypt"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_delete "${SERVICE_XPATH}"
        fi

        if [ -d OMV_LETSENCRYPT_APP_PATH ]; then
            find OMV_LETSENCRYPT_APP_PATH -mindepth 1 -delete
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
